index:
    path: /
    controller: App\Controller\GameController::menu

menu:
    path: /menu
    controller: App\Controller\GameController::menu

# Пользователь
registration_page:
    path: /registration
    controller: App\Controller\UserController::showRegistrationForm

register_user:
    path: /register
    controller: App\Controller\UserController::registerUser

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# Комната
room_list:
    path: /room-list
    controller: App\Controller\RoomController::roomList

room_create:
    path: /room/create
    controller: App\Controller\RoomController::createRoom

join_room:
    path: /room/join/{roomId}
    controller: App\Controller\RoomController::joinToRoom

show_room:
    path: /room/{roomId}
    controller: App\Controller\RoomController::showRoom

player_ready:
    path: /room/{roomId}/ready
    controller: App\Controller\RoomController::playerChangeReady

all_player_ready:
    path: /room/{roomId}/all-ready
    controller: App\Controller\RoomController::checkAllReady

# Игра
select-level:
    path: /select-level
    controller: App\Controller\GameController::selectLevel

singleplayer:
    path: /singleplayer
    controller: App\Controller\GameController::singleplayer

game:
    path: /game/room/{roomId}
    controller: App\Controller\GameController::game
