controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\GameController::menu

menu:
    path: /menu
    controller: App\Controller\GameController::menu

game:
    path: /game
    controller: App\Controller\GameController::game
    methods:

# Тестовый рут
publsih:
    path: /publish
    controller: App\Controller\PublishController:publish
