index:
    path: /
    controller: App\Controller\GameController::menu

menu:
    path: /menu
    controller: App\Controller\GameController::menu

game:
    path: /game
    controller: App\Controller\GameController::game
    methods:

