controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\GameController::menu

menu:
    path: /menu
    controller: App\Controller\GameController::menu

singleplayer:
    path: /singleplayer
    controller: App\Controller\GameController::singleplayer

game:
    path: /game
    controller: App\Controller\GameController::game
    methods:
